### ISSUE TITLE
Replicate All Notebooks in Jupyter to Google Colab - Moses

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#111]
**Reference:** https://glasswallsolu-qbp1117.slack.com/files/U0197EU3Q8M/F01AWN0BR0S/welcome_to_google_colab_-_video.mp4

**Comment by mnjenga2** [comment]
@chrisdiao I have shared the colab folder to your email.

**Comment by chrisdiao** [comment]
@mnjenga2 , I tried to check your notebook and encountered an error.

![image](https://user-images.githubusercontent.com/68153062/96246204-e5587980-0fda-11eb-937d-8e785e4937b1.png)
