### ISSUE TITLE
Enhance PR_report notebook filtering

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#116]
Enhance PR_report.ipynb notebook to enable users to filter the "Reviewer(s)" and or "Label(s)" column information.

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/849e68ed-e183-49ce-8d91-d7b7252eda2d)

**Comment by lucia15** [comment]
Filters should appear inside the notebook or in the .xlsx output file?

**Comment by chrisdiao** [comment]
@lucia15 , please check with @baker371 since he already came across with this, the filter should also be found in the notebook

**Comment by lucia15** [comment]
This one is ready, changes are available in colab

**Comment by chrisdiao** [comment]
great job @lucia15 ! Already seen the changes in colab. Can you also have this available in Jupyter notebook?

**Comment by lucia15** [comment]
Unfortunately the extension is only available on google colab

**Comment by chrisdiao** [comment]
This is well noted @lucia. Thanks!
