### ISSUE TITLE
Create a demo video related to issue #108/#115

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#117]
1. Create a demo video on how to user the application related to issue #108/#115.
2. Have it available in raw-videos channel
3. Notify Doviana and me

**Comment by lucia15** [comment]
I don't remember what those Issues were exactly about. Do you mean a demo video explaining how to run the notebooks? I plan to do it with the notebooks in Colab.

**Comment by chrisdiao** [comment]
@lucia15 , as discussed with our call earlier, the issue is related to Make_PowerPoint_Presentation and "Create new presentation for Daily Reports"

**Comment by chrisdiao** [comment]
Job well done @lucia15 !
For reference this is the [link](https://glasswallsolu-qbp1117.slack.com/archives/C0197C3EKKP/p1602707181003100) of the video.
