### ISSUE TITLE
Automatically create visual/report similar to attached 

### ISSUE THREAD

**Issue by markband** [k8-proxy/k8-data-visualization#12]
Objective: Write script that will automatically create a table report with the data shown in screenshot below. This is taken from k8-traffic-generator repo.

The input are the following:
1. List of resources assigned to the project with github usernames.
2. List of issues from Github repo with the status of each issue.

![image](https://user-images.githubusercontent.com/2129352/91508766-f8b86400-e90a-11ea-98a1-f8296e4938ae.png)

This task is done once we are able to automatically create a report in table format similar to attached.

**Comment by baker371** [comment]
I am on it

**Comment by baker371** [comment]
Currently the table looks like this, people are not setting milestones that would allow me capture the rest of the details

![tab](https://user-images.githubusercontent.com/8102313/92040758-a39fa680-ed7f-11ea-8b0b-45b87c814b09.PNG)

**Comment by dtollaku** [comment]
@baker371 you need to capture pipeline (nesw issue, backlog, in progress, etc) not milestone. And Mark on the table has the number of issues like #33 for example not the sum of the issues per assignee

**Comment by baker371** [comment]
Hello @dtollaku ,this is a list of all the columns with data that I pull from the repo, and I am finding it difficulty identifying which columns represent backlog, in progress,  review. Your guidance on the way forward is highly appreciated.

['url',
 'repository_url',
 'labels_url',
 'comments_url',
 'events_url',
 'html_url',
 'id',
 'node_id',
 'number',
 'title',
 'labels',
 'state',
 'locked',
 'assignee',
 'assignees',
 'milestone',
 'comments',
 'created_at',
 'updated_at',
 'closed_at',
 'author_association',
 'active_lock_reason',
 'body',
 'performed_via_github_app',
 'user.login',
 'user.id',
 'user.node_id',
 'user.avatar_url',
 'user.gravatar_id',
 'user.url',
 'user.html_url',
 'user.followers_url',
 'user.following_url',
 'user.gists_url',
 'user.starred_url',
 'user.subscriptions_url',
 'user.organizations_url',
 'user.repos_url',
 'user.events_url',
 'user.received_events_url',
 'user.type',
 'user.site_admin',
 'project',
 'pull_request.url',
 'pull_request.html_url',
 'pull_request.diff_url',
 'pull_request.patch_url',
 'assignee.login',
 'assignee.id',
 'assignee.node_id',
 'assignee.avatar_url',
 'assignee.gravatar_id',
 'assignee.url',
 'assignee.html_url',
 'assignee.followers_url',
 'assignee.following_url',
 'assignee.gists_url',
 'assignee.starred_url',
 'assignee.subscriptions_url',
 'assignee.organizations_url',
 'assignee.repos_url',
 'assignee.events_url',
 'assignee.received_events_url',
 'assignee.type',
 'assignee.site_admin',
 'milestone.url',
 'milestone.html_url',
 'milestone.labels_url',
 'milestone.id',
 'milestone.node_id',
 'milestone.number',
 'milestone.title',
 'milestone.description',
 'milestone.creator',
 'milestone.open_issues',
 'milestone.closed_issues',
 'milestone.state',
 'milestone.created_at',
 'milestone.updated_at',
 'milestone.due_on',
 'milestone.closed_at']

**Comment by chrisdiao** [comment]
@baker371 , could you please provide sample 3-5 data with header in a csv format. Thanks!

**Comment by dtollaku** [comment]
@baker371 we want this info that is found on the issue itself
![image](https://user-images.githubusercontent.com/29280857/92247001-dacc9f80-eec6-11ea-8f85-f11e928eb08b.png)

**Comment by chrisdiao** [comment]
@baker371 , if we cannot find that information in GitHub API, please check in Zenhub.
In ZenHub, I found this API documentation https://github.com/ZenHubIO/API#get-issue-data
![image](https://user-images.githubusercontent.com/68153062/92262406-a3351600-ef0d-11ea-9ecc-891fdaf218f2.png)
@dinis-cruz-gw , need your thought on this as well

**Comment by baker371** [comment]
> @baker371 we want this info that is found on the issue itself
> ![image](https://user-images.githubusercontent.com/29280857/92247001-dacc9f80-eec6-11ea-8f85-f11e928eb08b.png)

@dtollaku , Got it and on it. Thanks

**Comment by baker371** [comment]
> @baker371 , could you please provide 3-5 data with header in a csv format. Thanks!

@chrisdiao , I think this is no longer necessary, thanks for the API

**Comment by chrisdiao** [comment]
> > @baker371 , could you please provide 3-5 data with header in a csv format. Thanks!
> 
> @chrisdiao , I think this is no longer necessary, thanks for the API

@baker371 , in the future, we will need that for documentation purposes. We will build a mapping document so that other developers, QA and etc. will have a good reference.
For now please focus with the objective of this issue and let us know the progress.

**Comment by baker371** [comment]
Completed 
![zenhub 2](https://user-images.githubusercontent.com/8102313/93647075-355e1380-fa10-11ea-8dbc-2e9066bdcd22.png)
