### ISSUE TITLE
Data_analysis_and_visualization notebook is showing error

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#121]
The notebook is showing some error. Please check and do all necessary adjustment to fix the error.

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/89187fd0-7d0c-4f9a-9cd5-c8ce86657f32)

**Comment by baker371** [comment]
@chrisdiao this was the first draft create, it has been updated into issues.ipynb

**Comment by chrisdiao** [comment]
@baker371, on that case, we can already remove this notebook?
Please do all necessary action so that users will not be mislead.
