### ISSUE TITLE
issues notebook is showing some error

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#122]
The notebook is showing some error. Please check and do all necessary adjustments to fix the error.

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/e27654a4-802c-46e7-bbd8-d29a177e56aa)

**Comment by chrisdiao** [comment]
Found another error in this notebook.
![image](https://user-images.githubusercontent.com/68153062/96280139-35026980-100a-11eb-86fd-0a486ef9f7e1.png)

**Comment by chrisdiao** [comment]
Please test thoroughly before closing the issue.

**Comment by baker371** [comment]
@chrisdiao the notebooks have been optimized to run in google colab, so to run it locally some of the modules have to be installed locally, they are automatically installed in colab.

**Comment by chrisdiao** [comment]
@baker371 , we need also to have this running locally without any error. Remember, we are just replicating the work we have done to google colab, not migrating.

**Comment by chrisdiao** [comment]
@baker371 , encountered new error upon executing the notebook.
Please check again the implementation.
![image](https://user-images.githubusercontent.com/68153062/98144518-64b7d980-1f05-11eb-9529-1597b4bac76d.png)

**Comment by baker371** [comment]
@chrisdiao that was to demonstrate that you need to install google colab in your environment. Can you please install it in your working environment and comment out that line?
