### ISSUE TITLE
Visualise_Zenhub_Pipelines notebook is showing some error.

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#123]
The notebook is showing some error. Please check and do all necessary adjustment to fix the error.

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/cf72e308-95eb-46fa-8f8a-144379e8ab7f)

**Comment by baker371** [comment]
@chrisdiao to run this, you must 

pip install flatjson 

In your working environment.

**Comment by chrisdiao** [comment]
noted on this @baker371 , please include this on our guidelines so that the users will be guided accordingly. thaks!

**Comment by chrisdiao** [comment]
Found another error in this notebook.

![image](https://user-images.githubusercontent.com/68153062/96281030-5748b700-100b-11eb-99b9-381c2ffb8a43.png)

**Comment by chrisdiao** [comment]
Please test thoroughly before closing the issue.

**Comment by baker371** [comment]
Fixed.
