### ISSUE TITLE
Generate_files notebook is showing some error

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#136]
The notebook is showing some error. Please check and do all necessary adjustments to fix the error.

![image](https://user-images.githubusercontent.com/68153062/97164573-4a6f5480-17bd-11eb-8b91-1e3f354d0e09.png)

**Comment by lucia15** [comment]
The problem seems to be that 'Responsibility' column was erased from 'Project Team Structure' sheet, so I can just comment all lines related to that column and it will be fixed. But we have a new problem, because we need that information for the power point presentation...

**Comment by chrisdiao** [comment]
@dtollaku , we need your help regarding this error. As per @lucia15 , 'Responsibility' column was erased from 'Project Team Structure' google sheet.

**Comment by dtollaku** [comment]
@lucia15 we can remove the responsibility from both places, we will use only team members for everyone on the team, besides DM and stakehoder
