### ISSUE TITLE
Google Colab Generate_files is showing some error

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#144]
The notebook is showing some error. Please make sure Google Colab is always sync with Jupyter Notebook.

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/969fe76d-cedb-4914-bfc4-85d987f3c014)

**Comment by lucia15** [comment]
Solved!

**Comment by chrisdiao** [comment]
Thanks @lucia15 , I have check the google colab notebook today and error is no longer there.
