### ISSUE TITLE
7. Create Technical Documentation

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#32]
Create as much detailed technical documentation as possible (namely architecture and data-flow diagrams)
**E.g.:**
https://glasswallsolu-qbp1117.slack.com/files/U0167PD2VNK/F019S7B0H27/image.png

**Comment by chrisdiao** [comment]
@baker371 , could you please provide initial feedback on this issue.

**Comment by baker371** [comment]
![Uploading Issue_vis.png…]()

**Comment by baker371** [comment]
![token](https://user-images.githubusercontent.com/8102313/93817512-c37d0880-fc61-11ea-98f3-9a9386ab028d.png)

**Comment by baker371** [comment]
![download (6)](https://user-images.githubusercontent.com/8102313/94303745-02b79c00-ff77-11ea-906a-3e708dfd1ee6.png)

**Comment by baker371** [comment]
![visual](https://user-images.githubusercontent.com/8102313/94303961-63df6f80-ff77-11ea-8b3d-25aa6d786996.png)

**Comment by baker371** [comment]
![vis](https://user-images.githubusercontent.com/8102313/94304172-be78cb80-ff77-11ea-9577-9fb63011311d.png)

**Comment by baker371** [comment]
![zen5](https://user-images.githubusercontent.com/8102313/94305687-419b2100-ff7a-11ea-9760-a29fa58ec800.png)

**Comment by baker371** [comment]
@chrisdiao I am struggling writing documentation for the code I did not create, is it possible for every one to update the readme with the writeup on the usage of their code?

**Comment by baker371** [comment]
![plat](https://user-images.githubusercontent.com/8102313/94736551-18610300-0375-11eb-83d9-285577873479.png)
