### ISSUE TITLE
2. Write Tests for all APIs created

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#45]
Write Tests for all APIs created

**Comment by chrisdiao** [comment]
@baker371 & @GiuseMSD , how can we quantify this issue to be reviewed?
Where is the Test?

**Comment by baker371** [comment]
![cap](https://user-images.githubusercontent.com/8102313/93994382-7ea7bd80-fd98-11ea-8021-d03668d30485.png)

The test is right there
