### ISSUE TITLE
Create Org. Chart. Visualization

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#53]
**Requirements:**
- Converting this data to yaml files
- Add extra metadata , like its PST status (Pioneer, Settler or Town-planer)
- Creating visualization from those files

[Organization Chart.pdf](https://github.com/filetrust/k8-data-visualization/files/5196121/Organization.Chart.pdf)

For any questions or clarifications, please feel free to communicate Andres Jimenez.

**Comment by lucia15** [comment]
![sample_output2](https://user-images.githubusercontent.com/8679969/92986174-48606900-f48f-11ea-8a6f-ec151d0465a7.png)

**Comment by lucia15** [comment]
![sample_output3](https://user-images.githubusercontent.com/8679969/92986179-4f877700-f48f-11ea-8969-14dcfb15f9c9.png)

**Comment by lucia15** [comment]
![sample_output4](https://user-images.githubusercontent.com/8679969/92986185-58784880-f48f-11ea-8d06-753f22086fb6.png)
