### ISSUE TITLE
Visualization Chart

### ISSUE THREAD

**Issue by AmirahSukanty** [k8-proxy/k8-data-visualization#58]
[Organization Chart (2).docx](https://github.com/filetrust/k8-data-visualization/files/5208648/Organization.Chart.2.docx)

Please add PST [Pioneers, Settlers and Town-planners) and TT (Team Topologies) columns

**Comment by chrisdiao** [comment]
Hi @lucia15 , can you check this issue? I think this is related to issue #53 .
Please communicate with @AmirahSukanty .

**Comment by dtollaku** [comment]
Since the doc that @AmirahSukanty changes almost daily we need to have the source from the spreadsheet we use to update this, or a json file, when we can make changes. What is the best way to get this data for you @lucia15

**Comment by lucia15** [comment]
Ok, I'm working towards automatically convert spreadsheets to yaml files

**Comment by chrisdiao** [comment]
@lucia15 , please check this [link](https://docs.google.com/spreadsheets/d/1jX-FBOynt0A-uwVPk2EZRB2rsX3_c_2b/edit#gid=82649736) where data are being maintained.

**Comment by dtollaku** [comment]
@chrisdiao I have shared the link with @lucia15, but thanks for commenting here

**Comment by lucia15** [comment]
![generate_files](https://user-images.githubusercontent.com/8679969/93817041-c01c5980-fc2e-11ea-81db-32ee59d6c04f.png)
