### ISSUE TITLE
Apply Text2Code for Jupyter notebook - Lwasampijja

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#63]
Ref: https://towardsdatascience.com/data-analysis-made-easy-text2code-for-jupyter-notebook-5380e89bb493

**Comment by baker371** [comment]
@chrisdiao , is this about integrating text to code for the notebooks already created by me or everyone else?

**Comment by chrisdiao** [comment]
@baker371 only for the notebooks you have created.
