### ISSUE TITLE
Auto Create Org. Chart in Power Point

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#66]
1. I need automated way to create org chart in power point, which looks nice and easy to consume , source which always is updated is here https://docs.google.com/spreadsheets/d/1jX-FBOynt0A-uwVPk2EZRB2rsX3_c_2b/edit#gid=82649736 , I asked designer and he created following power point , which you can use as template or make improvements /suggestions to it.

[Template](https://glasswallsolu-qbp1117.slack.com/files/U01994MDS3U/F01BDEPLXH6/organization_chart_-_14th_sep.pptx)

2. I need a way to see when one engineer is involved in different projects easily

For inquiries or clarifications please feel free to contact  Tatevik Stepanyan

**Comment by lucia15** [comment]
I'm currently working on pulling data from that spreadsheet to create yaml and csv files
