### ISSUE TITLE
Create a report in Jupyter Notebook that will contain all in progress issues - 000001

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#81]
[Requirements](https://app.zenhub.com/files/289667349/2c27818b-cf10-4fcb-a0dc-0cccc9990765/download)

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/5936a9ac-c419-42d3-86c2-e84c9ec7e610)

**Comment by chrisdiao** [comment]
@baker371 , may I know the reason why you closed this issue? Is this done already?

**Comment by baker371** [comment]
@chrisdiao yes I completed it yesterday, I submited a review on slack
