### ISSUE TITLE
Create a Jupyter Notebook Table Content - Lucia

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#86]
Create a table content for all the works that you have done in Jupyter Notebook.

**Comment by lucia15** [comment]
where do I put the table of contents? in the README?

**Comment by chrisdiao** [comment]
The table content should be created in the notebook. 
Please check jupyter_contrib_nbextensions or other similar extension

![image](https://user-images.githubusercontent.com/68153062/94369206-ece2dc00-011a-11eb-8cac-55e62cddf0f5.png)
