### ISSUE TITLE
Enhance PR_report notebook – include label

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#98]
[Request](https://app.zenhub.com/files/289667349/233416ab-2007-4301-81a0-75babbc3a3f7/download)

![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/1cf05cd5-0eb7-4876-a672-74ed0571f2f7)

**Comment by lucia15** [comment]
I made changes so it exports data to an excel file like this:
![Uploading Captura de pantalla_2020-10-01_19-07-38.png…]()
is it correct?

**Comment by lucia15** [comment]
And looks like this in the jupyter-notebook:
![Captura de pantalla_2020-10-01_20-35-02](https://user-images.githubusercontent.com/8679969/94873519-cfb55280-0425-11eb-9f05-d7c4d66ee782.png)

**Comment by dtollaku** [comment]
Yes that is correct @lucia15
