### ISSUE TITLE
Create a report in Jupyter Notebook that will contain reporting for all assigned issues across multi reports

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-data-visualization#99]
- From all projects under k8-proxy repos, the following information is needed:
- A report that shows the issues that are assigned to a person across multiple repos, this will allow us to see any overlap of each engineer.

![image](https://user-images.githubusercontent.com/68153062/94581502-c30dee80-02ad-11eb-985f-6c06418b3fd1.png)

**Comment by baker371** [comment]
@GINAGC , notebook created can you inbox me your gmail so that I can invite you to the notebook.
